# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # El job 'build' original, pero sin el paso 'npm test'
  build:
    runs-on: ubuntu-latest
    
    # Define la matriz para la construcci칩n
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x] # Manteniendo tus versiones originales
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Show event trigger
        run: echo "Triggered by ${{ github.event_name }}"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: npm install and build webpack
        run: npm run build --if-present
      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: public/
  # El nuevo job 'test' que te proporcionaron
  test:
    runs-on: ${{ matrix.os }} # El SO es din치mico de la matriz
    
    # Depende de que el job 'build' haya terminado
    needs: build 
    
    # Define la matriz para las pruebas (diferente a la de 'build' en este ejemplo)
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [16.x, 18.x] # Usando las versiones del ejemplo que te dieron
        
    steps:
      - uses: actions/checkout@v3 # Nota: la versi칩n de checkout es diferente
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3 # Nota: la versi칩n de setup-node es diferente
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/download-artifact@main
        with:
          name: webpack artifacts
          path: public
      - name: npm install, and test
        run: |
          npm install
          npm test
        env:
          CI: true
